### PR TITLE
feat: add windows support

### PR DESCRIPTION
**Pull request by markthree**

### CODE REVIEW

**Comment by antfu** [comment]
Thanks. But can you revert the formatting and spaces changes?

**Comment by markthree** [comment]
OK, wait a minute 😂

**Comment by markthree** [comment]
It seems that I have to switch my formatting tool to eslint 😂

**Comment by markthree** [comment]
Format restored. Although it's not suitable to ask questions here, I want to know if you have a good reference for writing `vscode plugin`?

**Comment by antfu** [comment]
https://github.com/microsoft/vscode-extension-samples

**Comment by markthree** [comment]
thanks，You're the coolest person I've ever met

**Pull request merged**
